#!/usr/bin/perl
use strict;
use warnings;

my $arg = $ARGV[0];
unless ($arg) {
	die "Usage: encvim [filename]\n";
	exit 0;
}

my $enc_filename = $arg;
my $tmp_filename = '.' . $arg . '.tmp';
my $md5_original;

if (-e $enc_filename) {
	# Decrypt, calculate hash
	my $result = system qq|openssl enc -d -aes-256-cbc -in "$enc_filename" -out "$tmp_filename"|;
	unless ($result == 0) {
		print "Call to openssl returned with error code $result. Operation canceled.\n";
		exit -1;
	}
	$md5_original = `md5 $tmp_filename`;
} else {
	print "File $enc_filename does not exist. Create it? [Y/N] ";
	my $resp = <STDIN>;
	chomp $resp;
	$resp = uc $resp;
	unless ($resp eq 'Y') {
		print "Operation canceled.\n";
		exit 0;
	}
}

# Open
system("vim $tmp_filename");

# Encrypt and delete decrypted
if (`md5 $tmp_filename` eq $md5_original) {
	print "No changes.\n";
} else {
	my $result = system qq|openssl enc -aes-256-cbc -salt -in "$tmp_filename" -out "$enc_filename"|;
	unless ($result == 0) {
		print "Call to openssl returned with error code $result. Unable to encrypt. Changes lost.\n";
	}
}

`rm $tmp_filename`;

